import os
import re

# List of common TLDs without the dot
TLDs = [
    'com',
    'org',
    'net',
    'int',
    'edu',
    'gov',
    'mil',
    'co',
    'io',
    'ai',
    'app',
    'dev',
    'tech',
    'xyz',
    'me',
    'info',
    'biz',
    'online',
    'site',
    'store',
    'blog',
    'us',
    'uk',
    'ca',
    'de',
    'jp',
    'fr',
    'au',
    'in',
    'cn',
    'br',
    'ru',
    'ch',
    'nl',
    'se',
    'es',
    'it',
    'pl',
    'ir',
    'za',
    'mx',
    'kr',
    'tr',
    'ar',
    'sg',
    'id',
    'hk',
    'tv',
    'fm',
    'ly',
    'to',
    'ws',
    'cc',
    'mobi',
    'name',
    'pro',
    'jobs',
    'tel',
    'asia',
    'travel',
    'museum',
    'cat',
    'coop',
    'aero',
    'int',
    'bank',
    'insurance',
    'law',
    'health',
    'finance',
    'credit',
    'cloud',
    'design',
    'agency',
    'studio',
    'media',
    'news',
    'press',
    'today',
    'email',
    'group',
    'company',
    'team',
    'network',
    'support',
    'systems',
    'solutions',
    'capital',
    'ventures',
    'life',
    'world',
    'zone',
    'space',
    'tools',
    'cool',
    'ninja',
    'expert',
    'love',
    'fun',
    'party',
    'vip',
    'games',
    'social',
    'photo',
    'pics',
    'camera',
    'gallery',
    'art',
    'music',
    'film',
    'theatre',
    'dance',
    'bar',
    'cafe',
    'restaurant',
    'pizza',
    'beer',
    'fashion',
    'style',
    'beauty',
    'makeup',
    'build',
    'construction',
    'contractors',
    'engineering',
    'software',
    'digital',
    'computer',
    'technology',
    'academy',
    'school',
    'college',
    'university',
    'education',
    'church',
    'bible',
    'faith',
    'christmas',
    'loc', // For local domains
  ]

# Directory to search
ROOT_DIR = "vectors"

def is_tld_attached(filename):
    # Check if filename (without extension) ends in a known TLD and doesn't have a dot
    name, ext = os.path.splitext(filename)
    for tld in TLDs:
        if name.endswith(tld) and "." not in name:
            return True
    return False

for root, _, files in os.walk(ROOT_DIR):
    for file in files:
        if file.lower().endswith(".svg") and is_tld_attached(file):
            full_path = os.path.join(root, file)
            print(f"Suspicious: {full_path}")
